#include "../include/globals.h"

const int finenbin=100;
const float timemin=0.;
const float timemax=100.;
float biggesttime=0.;
float timecut=10;
float betacut=1/1.5;
int SCECOUNT=5;
int SCECOUNT2=20;
int icount777=0;
int SCECOUNT3=10;
int SCECOUNTHITHIT=1;
int ihitcounts=0;
int ihitcountc=0;
float egHcal=0.;
float meanscinHcal(0.),meancerHcal(0);
float meanSHcal(0.),meanCHcal(0.);
float meanscinEcal(0.),meancerEcal(0),egEcal(0.);
float meaneecaltimecut(0),meanerelecaltimecut(0);
float meanSEcal(0.),meanCEcal(0.);
float eesum(0.),eesumcal(0.),eesumem(0.),eesumair(0.),eesumdead(0.),eesumcrystal(0.),eesumPDe(0.),eesumfiber1(0.),eesumfiber2(0.),eesumabs(0.),eesumPDh(0.),eesumedge(0.),eesumedgerel(0.),necertotecal(0.),nescinttotecal(0.),necertothcal(0.),nescinttothcal(0.),eecaltimecut(0.),ehcaltimecut(0.),erelecaltimecut(0.),erelhcaltimecut(0.),eesumairem(0.),eesumdeadem(0.),eesumcrystalem(0.),eesumPDeem(0.),eesumfiber1em(0.),eesumfiber2em(0.),eesumabsem(0.),eesumPDhem(0.);
float meanehcaltimecut(0),meanerelhcaltimecut(0);
std::string aname_pd1_s[tfnx][tfny][tfndepth];
std::string aname_pd1_c[tfnx][tfny][tfndepth];
std::string aname_pd2_s[tfnx][tfny][tfndepth];
std::string aname_pd2_c[tfnx][tfny][tfndepth];
std::string anamee_pd1_s[tfnx][tfny][tfndepth];
std::string anamee_pd1_c[tfnx][tfny][tfndepth];
std::string anamee_pd2_s[tfnx][tfny][tfndepth];
std::string anamee_pd2_c[tfnx][tfny][tfndepth];
const char* bname_pd1_s[tfnx][tfny][tfndepth] = {nullptr};
const char* bname_pd1_c[tfnx][tfny][tfndepth] = {nullptr};
const char* bname_pd2_s[tfnx][tfny][tfndepth] = {nullptr};
const char* bname_pd2_c[tfnx][tfny][tfndepth] = {nullptr};
const char* bnamee_pd1_s[tfnx][tfny][tfndepth] = {nullptr};
const char* bnamee_pd1_c[tfnx][tfny][tfndepth] = {nullptr};
const char* bnamee_pd2_s[tfnx][tfny][tfndepth] = {nullptr};
const char* bnamee_pd2_c[tfnx][tfny][tfndepth] = {nullptr};
TH1F* timeframe_true_pd1_s[tfnx][tfny][tfndepth] = {nullptr};
TH1F* timeframe_true_pd1_c[tfnx][tfny][tfndepth] = {nullptr};
TH1F* timeframe_true_pd2_s[tfnx][tfny][tfndepth] = {nullptr};
TH1F* timeframe_true_pd2_c[tfnx][tfny][tfndepth] = {nullptr};
TH1F* timeframe_elec_pd1_s[tfnx][tfny][tfndepth] = {nullptr};
TH1F* timeframe_elec_pd1_c[tfnx][tfny][tfndepth] = {nullptr};
TH1F* timeframe_elec_pd2_s[tfnx][tfny][tfndepth] = {nullptr};
TH1F* timeframe_elec_pd2_c[tfnx][tfny][tfndepth] = {nullptr};
std::map<std::string, int> mapsampcalslice;